default_platform :ios

platform :ios do

lane :build do
 setup_travis
 match(type: "development")
 #scan
 gym(clean:true,scheme:"BankexWallet",configuration:"Debug",export_method:"development")
 crashlytics(api_token: "CRASHLYTICSTOKEN",
          build_secret: "CRASHLYTICSSECRET") 
end
end
